version: '3.8'

services:
  mariadb:
    image: mariadb:11.8.3
    container_name: mariadb-obstaclereports
    environment:
      - MARIADB_ROOT_PASSWORD=9991
      - MARIADB_DATABASE=obstaclereports
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=9991
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:                           # optional but recommended
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
  web:
    build:
      context: ./Project
      dockerfile: Dockerfile
    container_name: aspire-webapp
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OurDbConnection=Server=mariadb;Database=obstaclereports;User=admin;Password=9991;SslMode=None;

volumes:
  mariadb_data:
    driver: local
